### ISSUE TITLE
No weights allowed in runPSM

### ISSUE THREAD

**Issue by javier-sanchez-alvarez-roche** [Roche/Global-HTA-Evidence-Open#4]
runPSM function does not allow to implement weights in the regressions, which could be useful in the case of MAICs etc

**Comment by iain-t-bennett-roche** [comment]
This is now closed by https://github.com/Roche/flexsurvPlus/commit/f3b1f0389d4e3b1d616ab9b42ced113f1881f19e in the flexsurvPlus repository - version 1.03
